// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Script1</b><br>
 * Generated     : <b>2019/09/16 8:16:50 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 x86 10.0 <br>
 * 
 * @since  September 16, 2019
 * @author AG22518
 */
public abstract class Script1Helper extends RationalTestScript
{
	/**
	 * Afx400000202b1000360: with default state.
	 *		.text : null
	 * 		.class : Afx:400000:202b:10003:6:0
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject afx400000202b1000360window() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("afx400000202b1000360window"));
	}
	/**
	 * Afx400000202b1000360: with specific test context and state.
	 *		.text : null
	 * 		.class : Afx:400000:202b:10003:6:0
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject afx400000202b1000360window(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("afx400000202b1000360window"), anchor, flags);
	}
	
	/**
	 * Field_18_20: with default state.
	 *		.startRow : 18
	 * 		.startCol : 20
	 * 		.text :  
	 * 		.length : 1
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_18_20() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_18_20"));
	}
	/**
	 * Field_18_20: with specific test context and state.
	 *		.startRow : 18
	 * 		.startCol : 20
	 * 		.text :  
	 * 		.length : 1
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_18_20(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_18_20"), anchor, flags);
	}
	
	/**
	 * Field_21_15: with default state.
	 *		.startRow : 21
	 * 		.startCol : 15
	 * 		.text :                                                 
	 * 		.length : 48
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_21_15() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_21_15"));
	}
	/**
	 * Field_21_15: with specific test context and state.
	 *		.startRow : 21
	 * 		.startCol : 15
	 * 		.text :                                                 
	 * 		.length : 48
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_21_15(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_21_15"), anchor, flags);
	}
	
	/**
	 * Field_3_56: with default state.
	 *		.startRow : 3
	 * 		.startCol : 56
	 * 		.text : CHARS '071T9451910' foun
	 * 		.length : 24
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_3_56() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_3_56"));
	}
	/**
	 * Field_3_56: with specific test context and state.
	 *		.startRow : 3
	 * 		.startCol : 56
	 * 		.text : CHARS '071T9451910' foun
	 * 		.length : 24
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_3_56(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_3_56"), anchor, flags);
	}
	
	/**
	 * IBMExtensionForTerminalBasedApplications: with default state.
	 *		.captionText : IBM Extension for Terminal-based Applications
	 * 		accessibleContext.accessibleRole : frame
	 * 		.class : com.ibm.terminal.tester.gui.panel.TFrame
	 * 		accessibleContext.accessibleName : IBM Extension for Terminal-based Applications
	 */
	protected FTETopLevelTestObject ibmExtensionForTerminalBasedAp() 
	{
		return new FTETopLevelTestObject(
                        getMappedTestObject("ibmExtensionForTerminalBasedAp"));
	}
	/**
	 * IBMExtensionForTerminalBasedApplications: with specific test context and state.
	 *		.captionText : IBM Extension for Terminal-based Applications
	 * 		accessibleContext.accessibleRole : frame
	 * 		.class : com.ibm.terminal.tester.gui.panel.TFrame
	 * 		accessibleContext.accessibleName : IBM Extension for Terminal-based Applications
	 */
	protected FTETopLevelTestObject ibmExtensionForTerminalBasedAp(TestObject anchor, long flags) 
	{
		return new FTETopLevelTestObject(
                        getMappedTestObject("ibmExtensionForTerminalBasedAp"), anchor, flags);
	}
	
	/**
	 * MF1MyEXTRAEnterprise: with default state.
	 *		.text : MF1 - myEXTRA! Enterprise
	 * 		.class : SDIMainFrame
	 * 		.processName : EXTRA.exe
	 * 		.name : MF1 - myEXTRA! Enterprise
	 */
	protected TopLevelSubitemTestObject mF1MyEXTRAEnterprisewindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mF1MyEXTRAEnterprisewindow"));
	}
	/**
	 * MF1MyEXTRAEnterprise: with specific test context and state.
	 *		.text : MF1 - myEXTRA! Enterprise
	 * 		.class : SDIMainFrame
	 * 		.processName : EXTRA.exe
	 * 		.name : MF1 - myEXTRA! Enterprise
	 */
	protected TopLevelSubitemTestObject mF1MyEXTRAEnterprisewindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mF1MyEXTRAEnterprisewindow"), anchor, flags);
	}
	
	

	protected Script1Helper()
	{
		setScriptName("Script1");
	}
	
}

